version: '3'
services:

  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_NAME: DbName  
      WORDPRESS_DB_USER: DbUSER
      WORDPRESS_DB_PASSWORD: DbPASSWORD
      WORDPRESS_DB_HOST: DbHOST

volumes:
  db_data: {}
