version: '3.3'
services:
  wordpress:
    image: wordpress:latest
    volumes:
      - ./wordpress_files:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_NAME: DbName  
      WORDPRESS_DB_USER: DbUSER
      WORDPRESS_DB_PASSWORD: DbPASSWORD
      WORDPRESS_DB_HOST: DbHOST
      ACCESSKEY: IAMUserCredentials
      SECRETKEY: SECRETKEY
